version: 1
formatters:
    concise:
        format: '%(asctime)s - %(name)s - %(message)s'
        datefmt: '%H:%M:%S'
    precise:
        format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: concise

    pipeline_file:
        class : logging.handlers.RotatingFileHandler
        level: INFO
        formatter: precise
        filename: log/wtoa_pipeline.log
        maxBytes: 10485760  # 10MB
        backupCount: 20
        encoding: utf8

    error_file:
        class : logging.handlers.RotatingFileHandler
        level: WARNING
        formatter: precise
        filename: log/wtoa_error.log
        maxBytes: 1048576  # 1MB
        backupCount: 20
        encoding: utf8

loggers:
    # Pipeline logging
    pipeline:
        level: DEBUG
        handlers: [console, pipeline_file]

    # Peewee logging
    local.peewee.db:
        level: DEBUG
        handlers: [console]

    # Api logging
    walmart.apiuser:
        level: DEBUG
        handlers: [console, error_file]
